server.port : 9001
spring.application.name: hotel-service

spring.datasource.url: jdbc:postgresql://localhost:5432/HotelService
spring.datasource.username: postgres
spring.datasource.password: password
spring.jpa.show-sql: true

spring.jpa.hibernate.ddl-auto: update

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.data.jpa.repositories.enabled: true
logging.level.org.springframework.web: INFO


